<?php

namespace AppBundle\Repository;


/**
 * citoyenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class citoyenRepository extends \Doctrine\ORM\EntityRepository
{
	
}
