<?php

namespace AppBundle\Repository;

/**
 * EtatProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
