<?php

namespace AppBundle\Repository;

/**
 * GouvernoratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GouvernoratRepository extends \Doctrine\ORM\EntityRepository
{
}
