<?php

namespace AppBundle\Repository;

/**
 * imageProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class imageProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
