<?php

namespace AppBundle\Repository;

/**
 * LimiteSondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimiteSondageRepository extends \Doctrine\ORM\EntityRepository
{
}
