<?php

namespace AppBundle\Repository;

/**
 * ListeCommentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeCommentairesRepository extends \Doctrine\ORM\EntityRepository
{
}
