<?php

namespace AppBundle\Repository;

/**
 * ListeCitoyensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeRepository extends \Doctrine\ORM\EntityRepository
{
}
