<?php

namespace AppBundle\Repository;

/**
 * ReponnseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponnseRepository extends \Doctrine\ORM\EntityRepository
{
}
