<?php

namespace AppBundle\Repository;

/**
 * SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SondageRepository extends \Doctrine\ORM\EntityRepository
{
}
