<?php

namespace AppBundle\Repository;

/**
 * TokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenRepository extends \Doctrine\ORM\EntityRepository
{
}
