app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check

    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc    