
security:
    encoders:
        AppBundle\Entity\Citoyen: bcrypt
        AppBundle\Entity\Commune: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:Citoyen, property: email }

    firewalls: 
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       email
                password_parameter:       password    
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator  
        
        
        main:
            pattern: ^/
            logout:       true
            anonymous:    true


