
security:
    encoders:
        AppBundle\Entity\Citoyen: bcrypt
        AppBundle\Entity\Commune: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:Citoyen, property: email }
        users:    
            entity: { class: AppBundle:Commune, property: pseudo }

    firewalls: 
       


        # Citoyen
        api_Citoyen_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: database_users
            form_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: email
                password_parameter: password
 
        
        main:
            pattern: ^/
            anonymous:    true
            provider:  users
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /        


