
security:
    encoders:
        AppBundle\Entity\Citoyen: bcrypt
        AppBundle\Entity\Commune: bcrypt



    role_hierarchy:
        ROLE_UER:       ROLE_CITOYEN
        ROLE_ADMIN:     ROLE_COMMUNE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        users:    
            entity: { class: AppBundle:Commune, property: pseudo }

    firewalls: 



        api:
            pattern:   ^/api
            stateless: true
            anonymous: true 
            

        login:
            pattern:    ^/api/login
            stateless:  true
            anonymous:  true

            guard:
                authenticators:
                    - 'token_authenticator'


        
            
     
                
        
               
        main:
            pattern: ^/
            anonymous:    true
            provider:  users
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
 

 