
security:
    encoders:
        AppBundle\Entity\Citoyen: bcrypt
        AppBundle\Entity\Commune: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        api_register:
            pattern: ^/api/register
            anonymous: true
        login:
            pattern: ^/api/login
            logout:       true
            anonymous:    true
            form_login:
                check_path: /api/login_check
                username_parameter: _email
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            anonymous:    true
        
        
        main:
            pattern: ^/
            logout:       true
            anonymous:    true
    