
security:
    encoders:
        AppBundle\Entity\Citoyen: bcrypt



    role_hierarchy:
        ROLE_ADMIN:       ROLE_CITOYEN
        ROLE_SUPER_ADMIN: ROLE_cOMMUNE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        users:    
            entity: { class: AppBundle:Commune, property: pseudo }

    firewalls: 
        

        login:
            pattern:    ^/api/login
            stateless:  true
            anonymous:  true

            guard:
                authenticators:
                    - 'token_authenticator'
            
     
                
        
               
        main:
            pattern: ^/
            anonymous:    true
            provider:  users
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /logout
                target: /
 

